name: CI & CD
on:
    pull_request:
        types: [closed]
        branches:
            - master
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: output
              run: |
                  echo ${{ github.event.pull_request.labels.*.name}}
                  curl -X 'POST' \
                    'http://sd1leancloud.avosapps.us/goods/posttest' \
                    -H 'accept: application/json' \
                    -H 'Content-Type: application/json' \
                    -d '{
                      "some": ${{ github.event.pull_request.labels.*.name}}
                    }'
