name: CI & CD
on:
    pull_request:
        types: [closed]
        branches:
            - master
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Use Node.js
              env:
                  PR: ${{ github.event.pull_request }}
              run: |
                  node
                  console.log(${{ env.PR }});
