name: CI & CD
on:
    push:
        branches:
            - release
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get the LEANCLOUD_WEBHOOKS of secrets
              env:
                  LEANCLOUD_WEBHOOKS: ${{ secrets.LEANCLOUD_WEBHOOKS }}
              if: ${{ env.LEANCLOUD_WEBHOOKS }}
              uses: enflo/curl-action@v1.2
              with:
                  curl: -X POST ${{ secrets.LEANCLOUD_WEBHOOKS }}
