name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get the LEANCLOUD_WEBHOOKS of secrets
              env:
                  LEANCLOUD_WEBHOOKS: ${{ secrets.LEANCLOUD_WEBHOOKS }}
              if: ${{ env.LEANCLOUD_WEBHOOKS }}
              run: echo 'LEANCLOUD_WEBHOOKS is defined'
            - name: Checkout
              if: ${{ cancelled() }}
              uses: actions/checkout@v2
            - name: Use Node.js
              if: ${{ cancelled() }}
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install & build
              if: ${{ cancelled() }}
              run: |
                  npm install
                  npm run build
                  echo source/ >> .gitignore
                  echo \!dist/ >> .gitignore
            - name: Deploy
              if: ${{ cancelled() }}
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./
                  publish_branch: release
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  force_orphan: true
            - name: Deploy to LeanEngine
              if: ${{ cancelled() }}
              uses: enflo/curl-action@v1.2
              with:
                  curl: -X POST ${{ secrets.LEANCLOUD_WEBHOOKS }}
